### ISSUE TITLE
Error when running video - android

### ISSUE THREAD

**Issue by bradrice** [nstudio/nativescript-videoplayer#114]
I'm getting this error in the console, but the video plays. Any idea what might be causing this?

`
[30m[31m ERROR [0m ERROR Error: Uncaught (in promise): Error: java.lang.NullPointerException
    com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:111)
    android.media.MediaPlayer.setDataSource(MediaPlayer.java:1188)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
    com.tns.Runtime.callJSMethod(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:954)
    com.tns.Runtime.callJSMethod(Runtime.java:946)
    com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:17)
    org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
    org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
    android.os.Handler.handleCallback(Handler.java:789)
    android.os.Handler.dispatchMessage(Handler.java:98)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
Error: java.lang.NullPointerException
    com.android.internal.util.Preconditions.checkNotNull(Preconditions.java:111)
    android.media.MediaPlayer.setDataSource(MediaPlayer.java:1188)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1101)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:983)
    com.tns.Runtime.callJSMethod(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:954)
    com.tns.Runtime.callJSMethod(Runtime.java:946)
    com.tns.gen.org.nativescript.widgets.Async_CompleteCallback.onComplete(Async_CompleteCallback.java:17)
    org.nativescript.widgets.Async$Http$HttpRequestTask.onPostExecute(Async.java:585)
    org.nativescript.widgets.Async$Http$1$1.run(Async.java:486)
    android.os.Handler.handleCallback(Handler.java:789)
    android.os.Handler.dispatchMessage(Handler.java:98)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6541)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
    at file:///data/data/com.toolingu.class2tns/files/app/tns_modules/nativescript-audio/android/player.js:132:31
    at new ZoneAwarePromise (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777:29)
    at TNSPlayer.playFromFile (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/nativescript-audio/android/player.js:115:16)
    at file:///data/data/com.toolingu.class2tns/files/app/tns_modules/nativescript-audio/android/player.js:197:27
    at new ZoneAwarePromise (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:777:29)
    at TNSPlayer.playFromUrl (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/nativescript-audio/android/player.js:196:16)
    at PlayerService.playAudioTrack (file:///data/data/com.toolingu.class2tns/files/app/core/services/player.service.js:281:14)
    at SwitchMapSubscriber.project (file:///data/data/com.toolingu.class2tns/files/app/pages/player/audioControls/audio-controls.component.js:72:33)
    at SwitchMapSubscriber._next (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/rxjs/operators/switchMap.js:90:27)
    at SwitchMapSubscriber.Subscriber.next (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/rxjs/Subscriber.js:93:18)
    at DistinctUntilChangedSubscriber._next (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/rxjs/operators/distinctUntilChanged.js:103:30)
    at DistinctUntilChangedSubscriber.Subscriber.next (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/rxjs/Subscriber.js:93:18)
    at MapSubscriber._next (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/rxjs/operators/map.js:85:26)
    at MapSubscriber.Subscriber.next (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/rxjs/Subscriber.js:93:18)
    at BehaviorSubject.Subject.next (file:///data/data/com.toolingu.class2tns/files/app/tns_modules/rxjs/Subject.js:55:25)
`

This is how I am setting the video url:

`
initializeView(){
        this._videoPlayer = <Video>this.videoRef.nativeElement;
        this.playerService.disposeAudio();
        this.lesson$.subscribe(data=>{
            this.lessonDetail = data;
            this._videoPlayer.src = data['videoUrl'];
        },
        (err)=>{console.error(err)},
        ()=>{console.log('complete')}
        )`

**Comment by bradrice** [comment]
I solved this. It didn't have to do with the videoplayer at all, it was with the audioplayer that I was setting to play before unsetting it on the same page. I'm closing.
