### ISSUE TITLE
ios crash with migrate to ns8. Only in --release

### ISSUE THREAD

**Issue by bradrice** [nstudio/nativescript-videoplayer#206]
If I do ns debug ios -for-device --release --device <uuid> --provision <provision>

Video plugin works fine and plays video

If I do ns run ios --for-device --release --device <uuid> --provision <provision>

App runs fine except when i go to a page with the video plugin the app crashes.

Error in terminal:

`*** Terminating app due to uncaught exception 'NativeScript encountered a fatal error: Uncaught TypeError: e.error is not a function
at
defaultErrorLogger(file:///var/containers/Bundle/Application/2AEFBD35-AC59-4231-B944-31E6737F6BDD/classappnativescript.app/app/vendor.js:2:1897501)
at handleError(file:///var/containers/Bundle/Application/2AEFBD35-AC59-4231-B944-31E6737F6BDD/classappnativescript.app/app/vendor.js:2:1897697)
at next(file:///var/containers/Bundle/Application/2AEFBD35-AC59-4231-B944-31E6737F6BDD/classappnativescript.app/app/vendor.js:2:2089347)
at (file:///var/containers/Bundle/Application/2AEFBD35-AC59-4231-B944-31E6737F6BDD/classappnativescript.app/app/vendor.js:2:1495819)
at (file:///var/containers/Bundle/Application/2AEFBD35-AC59-4231-B944-31E6737F6BDD/classappnativescript.app/app/vendor.js:2:1495334)
at (file:///var/containers/Bundle/Application/2AEFBD35-AC59-4231-B944-31E6737F6BDD/classappnativescript.app/app/vendor.js:2:1494838)
at (file:///var/containers/Bundle/Applicat<\M-b\M^@\M-&>`

ns doctor:

`✔ Your ANDROID_HOME environment variable is set and points to correct directory.
✔ Your adb from the Android SDK is correctly installed.
✔ The Android SDK is installed.
✔ A compatible Android SDK for compilation is found.
✔ Javac is installed and is configured properly.
✔ The Java Development Kit (JDK) is installed and is configured properly.
✔ Xcode is installed and is configured properly.
✔ xcodeproj is installed and is configured properly.
✔ CocoaPods are installed.
✔ CocoaPods update is not required.
✔ CocoaPods are configured properly.
✔ Your current CocoaPods version is newer than 1.0.0.
✔ Python installed and configured correctly.
✔ The Python 'six' package is found.
✔ Xcode version 13.2.1 satisfies minimum required version 10.
✔ Getting NativeScript components versions information...
✔ Component nativescript has 8.2.2 version and is up to date.
✔ Component @nativescript/core has 8.2.1 version and is up to date.
✔ Component @nativescript/ios has 8.2.1 version and is up to date.
✔ Component @nativescript/android has 8.2.2 version and is up to date.`

**Comment by bradrice** [comment]
I'm sorry, upon further testing, this crash appears to be coming from an unset variable array on the same page. I'm working through the issue and will now close this issue. Apparently, the ios release is more strict than previously with handling this type of error.
